cards = {
  "Beatrice": {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'}, 
  "Alice": {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Mabel': {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Agnes': {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Henry': {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Nicholas': {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Elizabeth': {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Steve': {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'}, 
  'Emma': {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Richard': {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Cecilia': {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'John': {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Thomas': {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Geoffrey': {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Margaret': {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Isabella': {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'William': {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Edith': {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Matilda': {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Eleanor': {'age': 'Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Adam': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Earth', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'David': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Earth', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Elias': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Water', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Haimon': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Water', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Eric': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Air', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Hann': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Air', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
 'Herry': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Fire', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Robert': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Fire', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Aldith': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Earth', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Amice': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Earth', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Dye': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Water', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Eda': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Water', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Isabel': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Air', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Malle': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Air', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Meggy': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Fire', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Mary': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Fire', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Randel': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Earth', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Pete': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Earth', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Royse': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Water', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Tenney': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Water', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Stacy': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Air', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Wilkin': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Air', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Wilbert': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Fire', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Johan': {'age': 'Middle Ages', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Fire', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Jack': {'age': 'Middle Ages', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Earth', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Bob': {'age': 'Middle Ages', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Earth', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Conrad': {'age': 'Middle Ages', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Water', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Deagal': {'age': 'Middle Ages', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Air', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Gerold': {'age': 'Middle Ages', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Fire', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Erasmus': {'age': 'Middle Ages', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Earth', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Nicolas': {'age': 'Middle Ages', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Fire', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Antonio': {'age': 'Middle Ages', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Air', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Alexis': {'age': 'Middle Ages', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Air', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Cristopher': {'age': 'Middle Ages', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Water', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Ella': {'age': 'Middle Ages', 'rarity': 'Epic', 'class': 'Horsemount', 'type': 'Earth', 'damage': 25, 'hp': 75, 'description': 'Great agility and strength'},
  'Godwin': {'age': 'Middle Ages', 'rarity': 'Epic', 'class': 'Horsemount', 'type': 'Earth', 'damage': 25, 'hp': 75, 'description': 'Great agility and strength'},
  'Erika': {'age': 'Middle Ages', 'rarity': 'Epic', 'class': 'Horsemount', 'type': 'Water', 'damage': 25, 'hp': 75, 'description': 'Great agility and strength'},
  'Genevieve': {'age': 'Middle Ages', 'rarity': 'Epic', 'class': 'Royal Guard', 'type': 'Water', 'damage': 50, 'hp': 50, 'description': 'An elite fighter'},
  'Florian': {'age': 'Middle Ages', 'rarity': 'Epic', 'class': 'Royal Guard', 'type': 'Air', 'damage': 50, 'hp': 50, 'description': 'An elite fighter'},
  'Gregory': {'age': 'Middle Ages', 'rarity': 'Epic', 'class': 'Royal Guard', 'type': 'Air', 'damage': 50, 'hp': 50, 'description': 'An elite fighter'},
  'RoyalHome': {'age': 'Middle Ages', 'rarity': 'Legendary', 'class': 'Royal Family', 'type': 'Fire', 'damage': 50, 'hp': 100, 'description': 'Family of the great King'},
  'HenryIII': {'age': 'Middle Ages', 'rarity': 'Legendary', 'class': 'Ruler', 'type': 'Fire', 'damage': 75, 'hp': 125, 'description': 'The great king'},
  'KingArthur': {'age': 'Middle Ages', 'rarity': 'Mythic', 'class': 'Legend', 'type': 'Avatar', 'damage': 75, 'hp': 150, 'description': 'The Myth, The Man, The Legend'},
  'Kobayakawa': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Yamana': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Uesugi': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Tsukushi': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Munakata': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Yashiro': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Sano': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Koriki': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Shiba': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Yamaoka': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Kawakami': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Naito': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Kaneko': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Hasebe': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Itami': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Rokkaku': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Yamaguchi': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Iwashita': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Morikawa': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Enya': {'age': 'Japanese Middle Ages', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Okabe': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Earth', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Taira': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Earth', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Nakayama': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Water', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Möri': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Water', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Wada': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Air', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Yonezu': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Air', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Kano': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Fire', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Matsuura': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Fire', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Kira': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Earth', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Kimura': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Earth', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Nomura': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Water', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Takenaka': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Water', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Otawara': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Air', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Goto': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Air', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'arima': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Fire', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Hara': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Fire', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Soma': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Earth', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Nakajima': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Earth', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Yamada': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Water', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Sakakibara': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Water', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Iwakaki': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Air', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Ryuzoji': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Air', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Yuki': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Fire', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Umewaka': {'age': 'Japanese Middle Ages', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Fire', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Kawabe': {'age': 'Japanese Middle Ages', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Earth', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Hori': {'age': 'Japanese Middle Ages', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Earth', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Sen': {'age': 'Japanese Middle Ages', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Water', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Kitagaki': {'age': 'Japanese Middle Ages', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Air', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Hayashi': {'age': 'Japanese Middle Ages', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Fire', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Ogasawara': {'age': 'Japanese Middle Ages', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Earth', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Jo': {'age': 'Japanese Middle Ages', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Fire', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Kato': {'age': 'Japanese Middle Ages', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Air', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Takahashi': {'age': 'Japanese Middle Ages', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Air', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Oda': {'age': 'Japanese Middle Ages', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Water', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Yamamoto': {'age': 'Japanese Middle Ages', 'rarity': 'Epic', 'class': 'Horsemount', 'type': 'Earth', 'damage': 25, 'hp': 75, 'description': 'Great agility and strength'},
  'Yanagizawa': {'age': 'Japanese Middle Ages', 'rarity': 'Epic', 'class': 'Horsemount', 'type': 'Earth', 'damage': 25, 'hp': 75, 'description': 'Great agility and strength'},
  'Ota': {'age': 'Japanese Middle Ages', 'rarity': 'Epic', 'class': 'Horsemount', 'type': 'Water', 'damage': 25, 'hp': 75, 'description': 'Great agility and strength'},
  'Ito': {'age': 'Japanese Middle Ages', 'rarity': 'Epic', 'class': 'Royal Guard', 'type': 'Water', 'damage': 50, 'hp': 50, 'description': 'An elite fighter'},
  'Gö': {'age': 'Japanese Middle Ages', 'rarity': 'Epic', 'class': 'Royal Guard', 'type': 'Air', 'damage': 50, 'hp': 50, 'description': 'An elite fighter'},
  'Baba': {'age': 'Japanese Middle Ages', 'rarity': 'Epic', 'class': 'Royal Guard', 'type': 'Air', 'damage': 50, 'hp': 50, 'description': 'An elite fighter'},
  'Nagako': {'age': 'Japanese Middle Ages', 'rarity': 'Legendary', 'class': 'Royal Family', 'type': 'Air', 'damage': 50, 'hp': 100, 'description': 'Family of the great King'},
  'Hirohito': {'age': 'Japanese Middle Ages', 'rarity': 'Legendary', 'class': 'Ruler', 'type': 'Air', 'damage': 75, 'hp': 125, 'description': 'The great king'},
  'Goku': {'age': 'Japanese Middle Ages', 'rarity': 'Mythic', 'class': 'Legend', 'type': 'Avatar', 'damage': 75, 'hp': 150, 'description': 'The Myth, The man, The Legend'},
  'Drusus': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Corus': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Secundus': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Camillus': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Satyr': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Herennius': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Zosimus': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Rustica': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Gallus': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Phileros': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Scodopo': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Gemellus': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Phosphorus': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Saturnicus': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Actius': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Ceius': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Amethystus': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Veneleius': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Megiste': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Valens': {'age': 'Roman Empire', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Romulus': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Earth', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Amor': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Earth', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Samius': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Water', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Acretes': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Water', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Aegyptus': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Air', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Sittius': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Air', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Amianthus': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Fire', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Paris': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Fire', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Vera': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Earth', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Tettius': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Earth', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Antonius': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Water', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Myrtis': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Water', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Martha': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Air', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Theophilos': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Air', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Oceanus': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Fire', 'damage': 15, 'hp': 20, 'description': 'Magical brewer'},
  'Pallade': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Fire', 'damage': 15, 'hp': 20, 'description': 'Magical brewer'},
  'Quartilla': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Earth', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Damoetas': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Earth', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Nicerate': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Water', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Archaius': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Water', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Cornelius': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Air', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Irene': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Air', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Argos': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Fire', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Aegeus': {'age': 'Roman Empire', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Fire', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Zoe': {'age': 'Roman Empire', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Earth', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Albus': {'age': 'Roman Empire', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Earth', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Eudoxia': {'age': 'Roman Empire', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Water', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Celius': {'age': 'Roman Empire', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Air', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Julius': {'age': 'Roman Empire', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Fire', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Cupid': {'age': 'Roman Empire', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Earth', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Aridius': {'age': 'Roman Empire', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Fire', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Calix': {'age': 'Roman Empire', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Air', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Cyprian': {'age': 'Roman Empire', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Air', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Alpheus': {'age': 'Roman Empire', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Water', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Caius': {'age': 'Roman Empire', 'rarity': 'Epic', 'class': 'Horsemount', 'type': 'Earth', 'damage': 25, 'hp': 75, 'description': 'Great agility and strength'},
  'Barnabas': {'age': 'Roman Empire', 'rarity': 'Epic', 'class': 'Horsemount', 'type': 'Earth', 'damage': 25, 'hp': 75, 'description': 'Great agility and strength'},
  'Brutus': {'age': 'Roman Empire', 'rarity': 'Epic', 'class': 'Horsemount', 'type': 'Water', 'damage': 25, 'hp': 75, 'description': 'Great agility and strength'},
  'Amadeus': {'age': 'Roman Empire', 'rarity': 'Epic', 'class': 'Royal Guard', 'type': 'Water', 'damage': 50, 'hp': 50, 'description': 'An elite fighter'},
  'Ambrosius': {'age': 'Roman Empire', 'rarity': 'Epic', 'class': 'Royal Guard', 'type': 'Air', 'damage': 50, 'hp': 50, 'description': 'An elite fighter'},
  'Neptunus': {'age': 'Roman Empire', 'rarity': 'Epic', 'class': 'Royal Guard', 'type': 'Air', 'damage': 50, 'hp': 50, 'description': 'An elite fighter'},
  'Cleopatra': {'age': 'Roman Empire', 'rarity': 'Legendary', 'class': 'Royal Family', 'type': 'Earth', 'damage': 50, 'hp': 100, 'description': 'Family of the great King'},
  'Ceasar': {'age': 'Roman Empire', 'rarity': 'Legendary', 'class': 'Ruler', 'type': 'Earth', 'damage': 75, 'hp': 125, 'description': 'The great king'},
  'Christus': {'age': 'Roman Empire', 'rarity': 'Mythic', 'class': 'Legend', 'type': 'Avatar', 'damage': 75, 'hp': 150, 'description': 'The Myth, The man, The Legend'},
  'Karsten': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Halley': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Boe': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Stefan': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Ihor': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Lidwina': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Harold': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Denby': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Rafe': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Iver': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Unemployed', 'type': 'None', 'damage': 5, 'hp': 10, 'description': 'A commoner from medieval times, just your average individual. Do not expect much in terms of strength, but they will still give it their all in a fight!'},
  'Hansel': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Hagan': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Morten': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Ingemar': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Boden': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Commoner', 'type': 'None', 'damage': 7, 'hp': 13, 'description': 'A great addition to society'},
  'Kirsten': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Tyra': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Aina': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Jansen': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Ari': {'age': 'The Viking Age', 'rarity': 'Common', 'class': 'Commoner', 'type': 'Earth', 'damage': 7, 'hp': 14, 'description': 'A great addition to society'},
  'Larson': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Earth', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Rayne': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Earth', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Rayna': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Water', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Leif': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Water', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Kiersten': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Air', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Mikael': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Air', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Gunda': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Fire', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Espen': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Knight', 'type': 'Fire', 'damage': 10, 'hp': 17, 'description': 'A brave soldier'},
  'Valkyrie': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Earth', 'damage': 15, 'hp': 20, 'description': 'Magical brewer'},
  'Ander': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Earth', 'damage': 15, 'hp': 20, 'description': 'Magical brewer'},
  'Han': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Water', 'damage': 15, 'hp': 20, 'description': 'Magical brewer'},
  'Kristian': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Water', 'damage': 15, 'hp': 20, 'description': 'Magical brewer'},
  'Ralph': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Air', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Karina': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Air', 'damage': 15, 'hp': 20, 'description': 'A magical brewer'},
  'Bertil': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Fire', 'damage': 15, 'hp': 20, 'description': 'Magical brewer'},
  'Hanson': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Witch', 'type': 'Fire', 'damage': 15, 'hp': 20, 'description': 'Magical brewer'},
  'Gerd': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Earth', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Ivar': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Earth', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Anderso': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Water', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Denny': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Water', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Anders': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Air', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Treina': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Air', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Bjorn': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Fire', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Ingrid': {'age': 'The Viking Age', 'rarity': 'Uncommon', 'class': 'Assasin', 'type': 'Fire', 'damage': 40, 'hp': 10, 'description': 'As sly as a fox'},
  'Bowden': {'age': 'The Viking Age', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Earth', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Ursuline': {'age': 'The Viking Age', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Earth', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Eilert': {'age': 'The Viking Age', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Water', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Kristina': {'age': 'The Viking Age', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Air', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Thora': {'age': 'The Viking Age', 'rarity': 'Rare', 'class': 'Archer', 'type': 'Fire', 'damage': 15, 'hp': 40, 'description': 'A master with a bow'},
  'Hilda': {'age': 'The Viking Age', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Earth', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Solveig': {'age': 'The Viking Age', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Fire', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Wayde': {'age': 'The Viking Age', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Air', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Ulrika': {'age': 'The Viking Age', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Air', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Lefa': {'age': 'The Viking Age', 'rarity': 'Rare', 'class': 'Priest', 'type': 'Water', 'damage': 20, 'hp': 20, 'description': 'A great support on the battlefield'},
  'Jensen': {'age': 'The Viking Age', 'rarity': 'Epic', 'class': 'Horsemount', 'type': 'Earth', 'damage': 25, 'hp': 75, 'description': 'Great agility and strength'},
  'Kaia': {'age': 'The Viking Age', 'rarity': 'Epic', 'class': 'Horsemount', 'type': 'Earth', 'damage': 25, 'hp': 75, 'description': 'Great agility and strength'},
  'Norna': {'age': 'The Viking Age', 'rarity': 'Epic', 'class': 'Horsemount', 'type': 'Water', 'damage': 25, 'hp': 75, 'description': 'Great agility and strength'},
  'Ursule': {'age': 'The Viking Age', 'rarity': 'Epic', 'class': 'Royal Guard', 'type': 'Water', 'damage': 50, 'hp': 50, 'description': 'An elite fighter'},
  'Jenson': {'age': 'The Viking Age', 'rarity': 'Epic', 'class': 'Royal Guard', 'type': 'Air', 'damage': 50, 'hp': 50, 'description': 'An elite fighter'},
  'Bjarne': {'age': 'The Viking Age', 'rarity': 'Epic', 'class': 'Royal Guard', 'type': 'Air', 'damage': 50, 'hp': 50, 'description': 'An elite fighter'},
  'Frigga' : {'age': 'The Viking Age', 'rarity': 'Legendary', 'class': 'Royal Family', 'type': 'Water', 'damage': 50, 'hp': 100, 'description': 'Family of the great King'},
  'Odin': {'age': 'The Viking Age', 'rarity': 'Legendary', 'class': 'Ruler', 'type': 'Water', 'damage': 75, 'hp': 125, 'description': 'The great king'},
  'Thor': {'age': 'The Viking Age', 'rarity': 'Mythic', 'class': 'Legend', 'type': 'Avatar', 'damage': 75, 'hp': 150, 'description': 'The Myth, The man, The Legend'}
  }

PackableCommon = ['Beatrice', 'Alice', 'Mabel', 'Agnes', 'Henry', 'Nicholas', 'Elizabeth', 'Steve', 'Emma', 'Richard', 'Cecilia', 'John', 'Thomas', 'Geoffrey', 'Margaret', 'Isabella', 'William', 'Edith', 'Matilda', 'Eleanor', 'Kobayakawa', 'Yamana', 'Uesugi', 'Tsukushi', 'Munakata', 'Yashiro', 'Sano', 'Koriki', 'Shiba', 'Yamaoka', 'Kawakami', 'Naito', 'Kaneko', 'Hasebe', 'Itami', 'Rokkaku', 'Yamaguchi', 'Iwashita', 'Morikawa', 'Enya', 'Drusus', 'Corus', 'Secundus', 'Camillus', 'Satyr', 'Herennius', 'Zosimus', 'Rustica', 'Gallus', 'Phileros', 'Scodopo', 'Gemellus', 'Phosphorus', 'Saturnicus', 'Actius', 'Ceius', 'Amethystus', 'Veneleius', 'Megiste', 'Valens', 'Karsten', 'Halley', 'Boe', 'Stefan', 'Ihor', 'Lidwina', 'Harold', 'Denby', 'Rafe', 'Iver', 'Hansel', 'Hagan', 'Morten', 'Ingemar', 'Boden', 'Kirsten', 'Tyra', 'Aina', 'Jansen', 'Ari']

PackableUncommon = ['Adam', 'David', 'Elias', 'Haimon', 'Eric', 'Hann', 'Herry', 'Robert', 'Aldith', 'Amice', 'Dye', 'Eda', 'Isabel', 'Malle', 'Meggy', 'Mary', 'Randel', 'Pete', 'Royse', 'Tenney', 'Stacy', 'Wilkin', 'Wilbert', 'Johan', 'Okabe', 'Taira', 'Nakayama', 'Möri', 'Wada', 'Yonezu', 'Kano', 'Matsuura', 'Kira', 'Kimura', 'Nomura', 'Takenaka', 'Otawara', 'Goto', 'arima', 'Hara', 'Soma', 'Nakajima', 'Yamada', 'Sakakibara', 'Iwakaki', 'Ryuzoji', 'Yuki', 'Umewaka', 'Romulus', 'Amor', 'Samius', 'Acretes', 'Aegyptus', 'Sittius', 'Amianthus', 'Paris', 'Vera', 'Tettius', 'Antonius', 'Myrtis', 'Martha', 'Theophilos', 'Oceanus', 'Pallade', 'Quartilla', 'Damoetas', 'Nicerate', 'Archaius', 'Cornelius', 'Irene', 'Argos', 'Aegeus', 'Larson', 'Rayne', 'Rayna', 'Leif', 'Kiersten', 'Mikael', 'Gunda', 'Espen', 'Valkyrie', 'Ander', 'Han', 'Kristian', 'Ralph', 'Karina', 'Bertil', 'Hanson', 'Gerd', 'Ivar', 'Anderso', 'Denny', 'Anders', 'Treina', 'Bjorn', 'Ingrid']

PackableRare = ['Jack', 'Bob', 'Conrad', 'Deagal', 'Gerold', 'Erasmus', 'Nicolas', 'Antonio', 'Alexis', 'Cristopher', 'Kawabe', 'Hori', 'Sen', 'Kitagaki', 'Hayashi', 'Ogasawara', 'Jo', 'Kato', 'Takahashi', 'Oda', 'Zoe', 'Albus', 'Eudoxia', 'Celius', 'Julius', 'Cupid', 'Aridius', 'Calix', 'Cyprian', 'Alpheus', 'Bowden', 'Ursuline', 'Eilert', 'Kristina', 'Thora', 'Hilda', 'Solveig', 'Wayde', 'Ulrika', 'Lefa']

PackableEpic = ['Ella', 'Godwin', 'Erika', 'Genevieve', 'Florian', 'Gregory', 'Yamamoto', 'Yanagizawa', 'Ota', 'Ito', 'Gö', 'Baba', 'Caius', 'Barnabas', 'Brutus', 'Amadeus', 'Ambrosius', 'Neptunus', 'Jensen', 'Kaia', 'Norna', 'Ursule', 'Jenson', 'Bjarne']

PackableLegendary = ['RoyalHome', 'HenryIII', 'Nagako', 'Hirohito', 'Cleopatra', 'Ceasar', 'Frigga', 'Odin']

# very rare
PackableMythic = ['KingArthur', 'Goku', 'Christus', 'Thor']

# for card, data in cards.items():
#   if data['rarity'] == 'Common':
#     PackableCommon.append(card)
#   elif data['rarity'] == 'Uncommon':
#     PackableUncommon.append(card)
#   elif data['rarity'] == 'Rare':
#     PackableRare.append(card)
#   elif data['rarity'] == 'Epic':
#     PackableEpic.append(card)
#   elif data['rarity'] == 'Legendary':
#     PackableLegendary.append(card)
#   elif data['rarity'] == 'Mythic':
#     PackableMythic.append(card)

# print(PackableCommon)
# print(PackableUncommon)
# print(PackableRare)
# print(PackableEpic)
# print(PackableLegendary)
# print(PackableMythic)

# Steve 9 -> steve

rarity = {'Beatrice': 'Common', 'Alice': 'Common', 'Mabel': 'Common', 'Agnes': 'Common', 'Henry': 'Common', 'Nicholas': 'Common', 'Elizabeth': 'Common', 'Steve': 'Common', 'Emma': 'Common', 'Richard': 'Common', 'Cecilia': 'Common', 'John': 'Common', 'Thomas': 'Common', 'Geoffrey': 'Common', 'Margaret': 'Common', 'Isabella': 'Common', 'William': 'Common', 'Edith': 'Common', 'Matilda': 'Common', 'Eleanor': 'Common', 'Adam': 'Uncommon', 'David': 'Uncommon', 'Elias': 'Uncommon', 'Haimon': 'Uncommon', 'Eric': 'Uncommon', 'Hann': 'Uncommon', 'Herry': 'Uncommon', 'Robert': 'Uncommon', 'Aldith': 'Uncommon', 'Amice': 'Uncommon', 'Dye': 'Uncommon', 'Eda': 'Uncommon', 'Isabel': 'Uncommon', 'Malle': 'Uncommon', 'Meggy': 'Uncommon', 'Mary': 'Uncommon', 'Randel': 'Uncommon', 'Pete': 'Uncommon', 'Royse': 'Uncommon', 'Tenney': 'Uncommon', 'Stacy': 'Uncommon', 'Wilkin': 'Uncommon', 'Wilbert': 'Uncommon', 'Johan': 'Uncommon', 'Jack': 'Rare', 'Bob': 'Rare', 'Conrad': 'Rare', 'Deagal': 'Rare', 'Gerold': 'Rare', 'Erasmus': 'Rare', 'Nicolas': 'Rare', 'Antonio': 'Rare', 'Alexis': 'Rare', 'Cristopher': 'Rare', 'Ella': 'Epic', 'Godwin': 'Epic', 'Erika': 'Epic', 'Genevieve': 'Epic', 'Florian': 'Epic', 'Gregory': 'Epic', 'RoyalHome': 'Legendary', 'HenryIII': 'Legendary', 'KingArthur': 'Mythic', 'Kobayakawa': 'Common', 'Yamana': 'Common', 'Uesugi': 'Common', 'Tsukushi': 'Common', 'Munakata': 'Common', 'Yashiro': 'Common', 'Sano': 'Common', 'Koriki': 'Common', 'Shiba': 'Common', 'Yamaoka': 'Common', 'Kawakami': 'Common', 'Naito': 'Common', 'Kaneko': 'Common', 'Hasebe': 'Common', 'Itami': 'Common', 'Rokkaku': 'Common', 'Yamaguchi': 'Common', 'Iwashita': 'Common', 'Morikawa': 'Common', 'Enya': 'Common', 'Okabe': 'Uncommon', 'Taira': 'Uncommon', 'Nakayama': 'Uncommon', 'Möri': 'Uncommon', 'Wada': 'Uncommon', 'Yonezu': 'Uncommon', 'Kano': 'Uncommon', 'Matsuura': 'Uncommon', 'Kira': 'Uncommon', 'Kimura': 'Uncommon', 'Nomura': 'Uncommon', 'Takenaka': 'Uncommon', 'Otawara': 'Uncommon', 'Goto': 'Uncommon', 'arima': 'Uncommon', 'Hara': 'Uncommon', 'Soma': 'Uncommon', 'Nakajima': 'Uncommon', 'Yamada': 'Uncommon', 'Sakakibara': 'Uncommon', 'Iwakaki': 'Uncommon', 'Ryuzoji': 'Uncommon', 'Yuki': 'Uncommon', 'Umewaka': 'Uncommon', 'Kawabe': 'Rare', 'Hori': 'Rare', 'Sen': 'Rare', 'Kitagaki': 'Rare', 'Hayashi': 'Rare', 'Ogasawara': 'Rare', 'Jo': 'Rare', 'Kato': 'Rare', 'Takahashi': 'Rare', 'Oda': 'Rare', 'Yamamoto': 'Epic', 'Yanagizawa': 'Epic', 'Ota': 'Epic', 'Ito': 'Epic', 'Gö': 'Epic', 'Baba': 'Epic', 'Nagako': 'Legendary', 'Hirohito': 'Legendary', 'Goku': 'Mythic', 'Drusus': 'Common', 'Corus': 'Common', 'Secundus': 'Common', 'Camillus': 'Common', 'Satyr': 'Common', 'Herennius': 'Common', 'Zosimus': 'Common', 'Rustica': 'Common', 'Gallus': 'Common', 'Phileros': 'Common', 'Scodopo': 'Common', 'Gemellus': 'Common', 'Phosphorus': 'Common', 'Saturnicus': 'Common', 'Actius': 'Common', 'Ceius': 'Common', 'Amethystus': 'Common', 'Veneleius': 'Common', 'Megiste': 'Common', 'Valens': 'Common', 'Romulus': 'Uncommon', 'Amor': 'Uncommon', 'Samius': 'Uncommon', 'Acretes': 'Uncommon', 'Aegyptus': 'Uncommon', 'Sittius': 'Uncommon', 'Amianthus': 'Uncommon', 'Paris': 'Uncommon', 'Vera': 'Uncommon', 'Tettius': 'Uncommon', 'Antonius': 'Uncommon', 'Myrtis': 'Uncommon', 'Martha': 'Uncommon', 'Theophilos': 'Uncommon', 'Oceanus': 'Uncommon', 'Pallade': 'Uncommon', 'Quartilla': 'Uncommon', 'Damoetas': 'Uncommon', 'Nicerate': 'Uncommon', 'Archaius': 'Uncommon', 'Cornelius': 'Uncommon', 'Irene': 'Uncommon', 'Argos': 'Uncommon', 'Aegeus': 'Uncommon', 'Zoe': 'Rare', 'Albus': 'Rare', 'Eudoxia': 'Rare', 'Celius': 'Rare', 'Julius': 'Rare', 'Cupid': 'Rare', 'Aridius': 'Rare', 'Calix': 'Rare', 'Cyprian': 'Rare', 'Alpheus': 'Rare', 'Caius': 'Epic', 'Barnabas': 'Epic', 'Brutus': 'Epic', 'Amadeus': 'Epic', 'Ambrosius': 'Epic', 'Neptunus': 'Epic', 'Cleopatra': 'Legendary', 'Ceasar': 'Legendary', 'Christus': 'Mythic', 'Karsten': 'Common', 'Halley': 'Common', 'Boe': 'Common', 'Stefan': 'Common', 'Ihor': 'Common', 'Lidwina': 'Common', 'Harold': 'Common', 'Denby': 'Common', 'Rafe': 'Common', 'Iver': 'Common', 'Hansel': 'Common', 'Hagan': 'Common', 'Morten': 'Common', 'Ingemar': 'Common', 'Boden': 'Common', 'Kirsten': 'Common', 'Tyra': 'Common', 'Aina': 'Common', 'Jansen': 'Common', 'Ari': 'Common', 'Larson': 'Uncommon', 'Rayne': 'Uncommon', 'Rayna': 'Uncommon', 'Leif': 'Uncommon', 'Kiersten': 'Uncommon', 'Mikael': 'Uncommon', 'Gunda': 'Uncommon', 'Espen': 'Uncommon', 'Valkyrie': 'Uncommon', 'Ander': 'Uncommon', 'Han': 'Uncommon', 'Kristian': 'Uncommon', 'Ralph': 'Uncommon', 'Karina': 'Uncommon', 'Bertil': 'Uncommon', 'Hanson': 'Uncommon', 'Gerd': 'Uncommon', 'Ivar': 'Uncommon', 'Anderso': 'Uncommon', 'Denny': 'Uncommon', 'Anders': 'Uncommon', 'Treina': 'Uncommon', 'Bjorn': 'Uncommon', 'Ingrid': 'Uncommon', 'Bowden': 'Rare', 'Ursuline': 'Rare', 'Eilert': 'Rare', 'Kristina': 'Rare', 'Thora': 'Rare', 'Hilda': 'Rare', 'Solveig': 'Rare', 'Wayde': 'Rare', 'Ulrika': 'Rare', 'Lefa': 'Rare', 'Jensen': 'Epic', 'Kaia': 'Epic', 'Norna': 'Epic', 'Ursule': 'Epic', 'Jenson': 'Epic', 'Bjarne': 'Epic', 'Frigga': 'Legendary', 'Odin': 'Legendary', 'Thor': 'Mythic'}